name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - name: Check npm install exit code
        run: echo "npm install exited with $?"

      - uses: nrwl/nx-set-shas@v4

      - run: echo "Running lint, test, build"
      - run: npx nx affected -t lint test build
      - name: Check lint, test, build exit code
        run: echo "nx affected lint, test, build exited with $?"

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - run: echo "Running e2e-ci"
      - run: npx nx affected -t lint test build

      - run: npx nx affected --parallel 1 -t e2e-ci
      - name: Check e2e-ci exit code
        run: echo "nx affected e2e-ci exited with $?"
